name: grocery_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  flutter_staggered_grid_view: ^0.6.2
  grouped_list: ^5.1.2
  anim_search_bar: ^2.0.3
  syncfusion_flutter_datagrid: ^21.1.39
  animated_custom_dropdown: ^1.5.0
  dropdown_button2: ^2.1.0
  http:
  sticky_grouped_list: ^3.1.0
  google_fonts:
  cool_alert: ^2.0.1
  simple_form_builder:
  avatar_glow: ^2.0.2
  flutter_editable_table: ^1.1.1
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.10
  qr_flutter:
  pdf:
  printing:
  path_provider:
  flutter_datetime_picker:
  fp_bt_printer: ^0.0.3
  blue_thermal_printer: ^1.1.1
  esc_pos_utils:
  omni_datetime_picker: ^1.0.7
  gsform:
  time_picker_widget:
  fluttertoast: ^8.0.8
  provider:
  bluetooth_thermal_printer: ^0.0.6
  bluetooth_print:

  esc_pos_printer: ^4.0.0

  esc_pos_utils_plus:
  print_bluetooth_thermal: ^1.1.0
  flutter_html:
  flutter_dialogs:
  lottie:
  video_player:
  flutter_fast_forms:
  loading_animation_widget:
  flutter_glow:
  circular_clip_route:
  scaled_list:
  flutter_neumorphic:
  data_table_2: ^2.5.6
  share:
  syncfusion_flutter_pdf:
  file_picker:















dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0




flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/grocery_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/
    - assets/fonts/fake_receipt.otf
    - assets/fonts/Receiptional_Receipt_Regular.ttf
    - assets/fonts/FAKERECE.ttf



  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf

    - family: Receipt
      fonts:
      - asset: assets/fonts/fake_receipt.otf